config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :reviews


  resources :others do
    resources :reviews
  end

  resources :edibles do
    resources :reviews
  end

  resources :pre_rolls do
    resources :reviews
  end

  resources :flowers do
    resources :reviews
  end

  resources :indicas

  resources :sativas

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/edible.rb
class Edible < ApplicationRecord
  has_many :reviews, :as => :reviewable
  validates :name, presence: true
  validates :price, presence: true
  validates :thc, presence: true
  validates :description, presence: true
end

app/controllers/edibles_controller.rb
class EdiblesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  #
  # before_action :only => [:new, :edit] do
  #     redirect_to new_user_session_path unless current_user && current_user.admin
  #   end

  # GET /edibles
  # GET /edibles.json
  def index
    @edibles = Edible.all
  end

  # GET /edibles/1
  # GET /edibles/1.json
  def show
    @edible = Edible.find(params[:id])
  end

  # GET /edibles/new
  def new
    @edible = Edible.new
  end

  # GET /edibles/1/edit
  def edit
  end

  # POST /edibles
  # POST /edibles.json
  def create
    @edible = Edible.new(edible_params)

    respond_to do |format|
      if @edible.save
        format.html { redirect_to @edible, notice: 'Edible was successfully created.' }
        format.json { render :show, status: :created, location: @edible }
      else
        format.html { render :new }
        format.json { render json: @edible.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edibles/1
  # PATCH/PUT /edibles/1.json
  def update
    respond_to do |format|
      if @edible.update(edible_params)
        format.html { redirect_to @edible, notice: 'Edible was successfully updated.' }
        format.json { render :show, status: :ok, location: @edible }
      else
        format.html { render :edit }
        format.json { render json: @edible.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edibles/1
  # DELETE /edibles/1.json
  def destroy
    @edible.destroy
    respond_to do |format|
      format.html { redirect_to edibles_url, notice: 'Edible was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edible
      @edible = Edible.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edible_params
      params.require(:edible).permit(:name, :price, :thc, :description, :indica_id, :sativa_id)
    end
end

app/helpers/edibles_helper.rb
module EdiblesHelper
end

app/views/edibles/_form.html.erb
<%= form_with(model: edible, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :edible_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :edible_price %>
  </div>

  <div class="field">
    <%= form.label :thc %>
    <%= form.number_field :thc, id: :edible_thc %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :edible_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/edibles/edit.html.erb
<h1>Editing Edible</h1>

<%= render 'form', edible: @edible %>

<%= link_to 'Show', @edible %> |
<%= link_to 'Back', edibles_path %>

app/views/edibles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Edibles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Thc</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @edibles.each do |edible| %>
      <tr>
        <td><%= edible.name %></td>
        <td>$<%= edible.price %></td>
        <td><%= edible.thc %>%</td>
        <td><%= edible.description %></td>
        <td><%= link_to 'Show', edible %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Edit', edit_edible_path(edible) %></td>
        <td><%= link_to 'Destroy', edible, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.admin %>
<%= link_to 'New Edible', new_edible_path %>
<% end %>
<%= link_to 'Home', "/" %>

app/views/edibles/new.html.erb
<h1>New Edible</h1>

<%= render 'form', edible: @edible %>

<%= link_to 'Back', edibles_path %>

app/views/edibles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @edible.name %>
</p>

<p>
  <strong>Price:</strong>
  $<%=  @edible.price %>
</p>

<p>
  <strong>Thc:</strong>
  <%= @edible.thc %>%
</p>

<p>
  <strong>Description:</strong>
  <%= @edible.description %>
</p>

  <% if current_user && current_user.admin %>
  <%= link_to 'Edit', edit_edible_path(@edible) %> |
  <% end %>

<h3>Reviews</h3>
  <div class="row">
    <% if @edible.reviews.any? %>
      <% @edible.reviews.each do |review| %>
        <div class="col col-lg-4">
          <div class="card review">
            <div class="card-block">
                <h4 class="card-title"> <%= review.reviewer %> </h4>
                <p class="card-text"><%= review.review_content %> </p>
            </div>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>

<br>
<%= link_to 'Add Review', new_edible_review_path(@edible) %> |
<%= link_to 'Back', edibles_path %> |
<%= link_to 'Home', "/" %>