config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :reviews


  resources :others do
    resources :reviews
  end

  resources :edibles do
    resources :reviews
  end

  resources :pre_rolls do
    resources :reviews
  end

  resources :flowers do
    resources :reviews
  end

  resources :indicas

  resources :sativas

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/other.rb
class Other < ApplicationRecord
  has_many :reviews, :as => :reviewable
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/controllers/others_controller.rb
class OthersController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  #
  # before_action :only => [:new, :edit] do
  #     redirect_to new_user_session_path unless current_user && current_user.admin
  #   end

  # GET /others
  # GET /others.json
  def index
    @others = Other.all
  end

  # GET /others/1
  # GET /others/1.json
  def show
    @other = Other.find(params[:id])
  end

  # GET /others/new
  def new
    @other = Other.new
  end

  # GET /others/1/edit
  def edit
  end

  # POST /others
  # POST /others.json
  def create
    @other = Other.new(other_params)

    respond_to do |format|
      if @other.save
        format.html { redirect_to @other, notice: 'Other was successfully created.' }
        format.json { render :show, status: :created, location: @other }
      else
        format.html { render :new }
        format.json { render json: @other.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /others/1
  # PATCH/PUT /others/1.json
  def update
    respond_to do |format|
      if @other.update(other_params)
        format.html { redirect_to @other, notice: 'Other was successfully updated.' }
        format.json { render :show, status: :ok, location: @other }
      else
        format.html { render :edit }
        format.json { render json: @other.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /others/1
  # DELETE /others/1.json
  def destroy
    @other.destroy
    respond_to do |format|
      format.html { redirect_to others_url, notice: 'Other was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_other
      @other = Other.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def other_params
      params.require(:other).permit(:name, :price, :thc, :description, :indica_id, :sativa_id)
    end
end

app/helpers/others_helper.rb
module OthersHelper
end

app/views/others/_form.html.erb
<%= form_with(model: other, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :other_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :other_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :other_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/others/edit.html.erb
<h1>Editing Other</h1>

<%= render 'form', other: @other %>

<%= link_to 'Show', @other %> |
<%= link_to 'Back', others_path %>

app/views/others/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Others</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @others.each do |other| %>
      <tr>
        <td><%= other.name %></td>
        <td>$<%= other.price %></td>
        <td><%= other.description %>%</td>
        <td><%= link_to 'Show', other %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Edit', edit_other_path(other) %></td>
        <td><%= link_to 'Destroy', other, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.admin %>
<%= link_to 'New Other', new_other_path %>
<% end %>
<%= link_to 'Home', "/" %>

app/views/others/new.html.erb
<h1>New Other</h1>

<%= render 'form', other: @other %>

<%= link_to 'Back', others_path %>

app/views/others/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @other.name %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @other.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @other.description %>%
</p>





  <% if current_user && current_user.admin %>
    <%= link_to 'Edit', edit_other_path(@other) %> |
  <% end %>


<h3>Reviews</h3>
  <div class="row">
    <% if @other.reviews.any? %>
      <% @other.reviews.each do |review| %>
        <div class="col col-lg-4">
          <div class="card review">
            <div class="card-block">
                <h4 class="card-title"> <%= review.reviewer %> </h4>
                <p class="card-text"><%= review.review_content %> </p>
            </div>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>


<br>
<%= link_to 'Add Review', new_other_review_path(@other) %> |
<%= link_to 'Back', others_path %>|
<%= link_to 'Home', "/" %>