config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :reviews


  resources :others do
    resources :reviews
  end

  resources :edibles do
    resources :reviews
  end

  resources :pre_rolls do
    resources :reviews
  end

  resources :flowers do
    resources :reviews
  end

  resources :indicas

  resources :sativas

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flower.rb
class Flower < ApplicationRecord
  has_many :reviews, :as => :reviewable
  validates :name, presence: true
  validates :price, presence: true
  validates :thc, presence: true
  validates :description, presence: true
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  #
  # before_action :only => [:new, :edit] do
  #     redirect_to new_user_session_path unless current_user && current_user.admin
  #   end

  # GET /flowers
  # GET /flowers.json
  def index
    @flowers = Flower.all
  end

  # GET /flowers/1
  # GET /flowers/1.json
  def show
    @flower = Flower.find(params[:id])
  end

  # GET /flowers/new
  def new
    @flower = Flower.new
  end

  # GET /flowers/1/edit
  def edit
  end

  # POST /flowers
  # POST /flowers.json
  def create
    @flower = Flower.new(flower_params)

    respond_to do |format|
      if @flower.save
        format.html { redirect_to @flower, notice: 'Flower was successfully created.' }
        format.json { render :show, status: :created, location: @flower }
      else
        format.html { render :new }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flowers/1
  # PATCH/PUT /flowers/1.json
  def update
    respond_to do |format|
      if @flower.update(flower_params)
        format.html { redirect_to @flower, notice: 'Flower was successfully updated.' }
        format.json { render :show, status: :ok, location: @flower }
      else
        format.html { render :edit }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flowers/1
  # DELETE /flowers/1.json
  def destroy
    @flower.destroy
    respond_to do |format|
      format.html { redirect_to flowers_url, notice: 'Flower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flower
      @flower = Flower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flower_params
      params.require(:flower).permit(:name, :price, :thc, :description)
    end
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/views/flowers/_form.html.erb
<%= form_with(model: flower, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :flower_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :flower_price %>
  </div>

  <div class="field">
    <%= form.label :thc %>
    <%= form.number_field :thc, id: :flower_thc %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :flower_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flowers/edit.html.erb
<h1>Editing Flower</h1>

<%= render 'form', flower: @flower %>

<%= link_to 'Show', @flower %> |
<%= link_to 'Back', flowers_path %>

app/views/flowers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flowers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>THC</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flowers.each do |flower| %>
      <tr>
        <td><%= flower.name %></td>
        <td>$<%= flower.price %></td>
        <td><%= flower.thc %>%</td>
        <td><%= flower.description %></td>
        <td><%= link_to 'Show', flower %></td>
          <% if current_user && current_user.admin %>
          <td><%= link_to 'Edit', edit_flower_path(flower) %></td>
          <td><%= link_to 'Destroy', flower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user && current_user.admin %>
<%= link_to 'New Flower', new_flower_path %>
<% end %>
<%= link_to 'Home', "/" %>

app/views/flowers/new.html.erb
<h1>New Flower</h1>

<%= render 'form', flower: @flower %>

<%= link_to 'Back', flowers_path %>

app/views/flowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flower.name %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @flower.price %>
</p>

<p>
  <strong>Thc:</strong>
  <%=  @flower.thc %>%
</p>

<p>
  <strong>Description:</strong>
  <%= @flower.description %>
</p>

  <% if current_user && current_user.admin %>
    <%= link_to 'Edit', edit_flower_path(@flower) %> |
  <% end %>


  <br>

<h3>Reviews</h3>
  <div class="row">
    <% if @flower.reviews.any? %>
      <% @flower.reviews.each do |review| %>
        <div class="col col-lg-4">
          <div class="card review">
            <div class="card-block">
              <p class="card-text">"<%= review.review_content %>"</p>
              <h4 class="card-title"> - <%= review.reviewer %> </h4>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

<br>
<%= link_to 'Add Review', new_flower_review_path(@flower) %> |
<%= link_to 'Back', flowers_path %> |
<%= link_to 'Home', "/" %>