config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :reviews


  resources :others do
    resources :reviews
  end

  resources :edibles do
    resources :reviews
  end

  resources :pre_rolls do
    resources :reviews
  end

  resources :flowers do
    resources :reviews
  end

  resources :indicas

  resources :sativas

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pre_roll.rb
class PreRoll < ApplicationRecord
  has_many :reviews, :as => :reviewable
  validates :name, presence: true
  validates :price, presence: true
  validates :thc, presence: true
  validates :description, presence: true
end

app/controllers/pre_rolls_controller.rb
class PreRollsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  #
  # before_action :only => [:new, :edit] do
  #     redirect_to new_user_session_path unless current_user && current_user.admin
  #   end

  # GET /pre_rolls
  # GET /pre_rolls.json
  def index
    @pre_rolls = PreRoll.all
  end

  # GET /pre_rolls/1
  # GET /pre_rolls/1.json
  def show
    @pre_roll = PreRoll.find(params[:id])
  end

  # GET /pre_rolls/new
  def new
    @pre_roll = PreRoll.new
  end

  # GET /pre_rolls/1/edit
  def edit
  end

  # POST /pre_rolls
  # POST /pre_rolls.json
  def create
    @pre_roll = PreRoll.new(pre_roll_params)

    respond_to do |format|
      if @pre_roll.save
        format.html { redirect_to @pre_roll, notice: 'Pre roll was successfully created.' }
        format.json { render :show, status: :created, location: @pre_roll }
      else
        format.html { render :new }
        format.json { render json: @pre_roll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pre_rolls/1
  # PATCH/PUT /pre_rolls/1.json
  def update
    respond_to do |format|
      if @pre_roll.update(pre_roll_params)
        format.html { redirect_to @pre_roll, notice: 'Pre roll was successfully updated.' }
        format.json { render :show, status: :ok, location: @pre_roll }
      else
        format.html { render :edit }
        format.json { render json: @pre_roll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pre_rolls/1
  # DELETE /pre_rolls/1.json
  def destroy
    @pre_roll.destroy
    respond_to do |format|
      format.html { redirect_to pre_rolls_url, notice: 'Pre roll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pre_roll
      @pre_roll = PreRoll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pre_roll_params
      params.require(:pre_roll).permit(:name, :price, :thc, :description, :indica_id, :sativa_id)
    end
end

app/helpers/pre_rolls_helper.rb
module PreRollsHelper
end

app/views/pre_rolls/_form.html.erb
<%= form_with(model: pre_roll, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pre_roll_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :pre_roll_price %>
  </div>

  <div class="field">
    <%= form.label :thc %>
    <%= form.number_field :thc, id: :pre_roll_thc %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :pre_roll_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pre_rolls/edit.html.erb
<h1>Editing Pre Roll</h1>

<%= render 'form', pre_roll: @pre_roll %>

<%= link_to 'Show', @pre_roll %> |
<%= link_to 'Back', pre_rolls_path %>

app/views/pre_rolls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pre Rolls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Thc</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pre_rolls.each do |pre_roll| %>
      <tr>
        <td><%= pre_roll.name %></td>
        <td>$<%= pre_roll.price %></td>
        <td><%= pre_roll.thc %>%</td>
        <td><%= pre_roll.description %></td>
        <td><%= link_to 'Show', pre_roll %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Edit', edit_pre_roll_path(pre_roll) %></td>
        <td><%= link_to 'Destroy', pre_roll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.admin %>
<%= link_to 'New Pre Roll', new_pre_roll_path %>
<% end %>
<%= link_to 'Home', "/" %>

app/views/pre_rolls/new.html.erb
<h1>New Pre Roll</h1>

<%= render 'form', pre_roll: @pre_roll %>

<%= link_to 'Back', pre_rolls_path %>

app/views/pre_rolls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pre_roll.name %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @pre_roll.price %>
</p>

<p>
  <strong>THC:</strong>
  <%= @pre_roll.thc %>%
</p>

<p>
  <strong>Description:</strong>
  <%= @pre_roll.description %>
</p>

  <% if current_user && current_user.admin %>
<%= link_to 'Edit', edit_pre_roll_path(@pre_roll) %> |
  <% end %>

  <h3>Reviews</h3>
  <div class="row">
    <% if @pre_roll.reviews.any? %>
      <% @pre_roll.reviews.each do |review| %>
        <div class="col col-lg-4">
          <div class="card review">
            <div class="card-block">
                <h4 class="card-title"> <%= review.reviewer %> </h4>
                <p class="card-text"><%= review.review_content %> </p>
            </div>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>

<br>
<%= link_to 'Add Review', new_pre_roll_review_path(@pre_roll) %>
<%= link_to 'Back', pre_rolls_path %>
<%= link_to 'Home', "/" %>